core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

course/urls.py
from django.urls import path

from .views import \
    course_list_view, \
    course_view, \
    lab_new_view, \
    lab_view, \
    lab_evaluation_view, \
    lab_evaluation_submit_view, \
    lab_evaluation_total_view, \
    lab_submit_view, \
    stu_tree_view, \
    stu_blob_view

urlpatterns = [
    path('', course_list_view, name='courses'),
    path('<int:course_id>', course_view, name='course'),
    path('<int:course_id>/lab/new', lab_new_view, name='lab_new'),
    path('<int:course_id>/lab/<int:lab_id>', lab_view, name='lab'),
    path('<int:course_id>/lab/<int:lab_id>/evaluation', lab_evaluation_view, name='lab_evaluation'),
    path('<int:course_id>/lab/<int:lab_id>/evaluationTotal', lab_evaluation_total_view,
         name='lab_eva_total'),
    path('<int:course_id>/lab/<int:lab_id>/evaluation/<str:student>', lab_evaluation_submit_view,
         name='lab_eva_submit'),
    path('<int:course_id>/lab/<int:lab_id>/submit', lab_submit_view, name='lab_submit'),
    path('<int:course_id>/lab/<int:lab_id>/submit/<str:student>/<str:project>/-/tree/', stu_tree_view,
         name='stu_tree_root'),
    path('<int:course_id>/lab/<int:lab_id>/submit/<str:student>/<str:project>/-/tree/<path:path>/', stu_tree_view,
         name='stu_tree'),
    path('<int:course_id>/lab/<int:lab_id>/submit/<str:student>/<str:project>/-/blob/<path:path>/', stu_blob_view,
         name='stu_blob'),
]

flowlab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('course/', include('course.urls')),
    path('flow/', include('flow.urls')),
]

course/models.py
from django.db import models

from core.models import Semester
from accounts.models import Teacher, Student
from flow.models import Project, Template


class Course(models.Model):
    semester = models.ForeignKey(
        Semester,
        on_delete=models.CASCADE,
        null=True,
        verbose_name='學期',
    )
    name = models.CharField('課程名稱', max_length=50)
    teacher = models.ForeignKey(
        Teacher,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='指導老師',
    )
    students = models.ManyToManyField(Student, blank=True, verbose_name='學生')

    class Meta:
        unique_together = ['semester', 'name']
        verbose_name = verbose_name_plural = '課程'

    def __str__(self):
        return f'{self.semester}/{self.name}'


class Lab(models.Model):
    name = models.CharField('實驗名稱', max_length=50)
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        verbose_name='關聯課程',
    )
    project = models.ManyToManyField(Project, blank=True)
    template = models.ForeignKey(
        Template,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='套用模板',
    )
    branch = models.CharField('繳交分支', max_length=72)
    description = models.TextField('實驗描述', blank=True)
    deadline = models.DateTimeField('繳交期限', blank=True, null=True)

    class Meta:
        unique_together = ['course', 'name']
        verbose_name = verbose_name_plural = '實驗'

    def __str__(self):
        return f'{self.course.name}/{self.name}'


class Question(models.Model):
    QUESTION_TYPES = (
        ('text', '問答題'),
        ('single', '單選題'),
    )

    type = models.CharField('題目類型', max_length=25, choices=QUESTION_TYPES)
    content = models.CharField('題目內容', max_length=256)
    lab = models.ForeignKey(
        Lab,
        on_delete=models.CASCADE,
        verbose_name='實驗',
    )
    number = models.DecimalField('編號', decimal_places=0, max_digits=3)

    class Meta:
        unique_together = ['lab', 'id']
        verbose_name = verbose_name_plural = '題目'

    def __str__(self):
        return f'{self.content}'


class Option(models.Model):
    content = models.CharField('選項內容', max_length=256)
    topic = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        verbose_name='題目',
    )
    number = models.DecimalField('編號', decimal_places=0, max_digits=2)

    class Meta:
        unique_together = ['topic', 'number']
        verbose_name = verbose_name_plural = '選項'

    def __str__(self):
        return f'{self.content}'


class Answer(models.Model):
    content = models.CharField('答案', max_length=256)
    topic = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        verbose_name='題目',
    )
    student = models.ForeignKey(
        Student,
        on_delete=models.CASCADE,
        verbose_name='學生',
    )

    class Meta:
        unique_together = ['student', 'topic']
        verbose_name = verbose_name_plural = '答案'

    def __str__(self):
        return f'{self.content}'

course/forms.py
from django import forms
from django.contrib.admin.widgets import AdminSplitDateTime

from .models import Lab


class LabForm(forms.ModelForm):
    deadline = forms.SplitDateTimeField(
        widget=forms.SplitDateTimeWidget(attrs={
            'class': 'd-flex justify-content-start',
            # FIXME: 繳交期限無法'選填'
        }),
    )

    class Meta:
        model = Lab
        fields = ['name', 'description', 'branch', 'template', 'deadline']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'strip': True,
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 5,
                'strip': True,
                'required': False,
            }),
            'branch': forms.TextInput(attrs={
                'class': 'form-control',
                'strip': True,
            }),
            'template': forms.Select(attrs={
                'required': False,
            }),
        }

course/views.py
import csv
import os
from pathlib import PurePosixPath

from gitlab.exceptions import GitlabGetError

from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import JsonResponse, Http404, HttpResponse

from accounts.models import Role, Teacher, Student
from accounts.utils.check_role import get_roles, check_role
from core.dicts import MESSAGE_DICT
from core.infra import GITLAB_, SONAR_
from core.infra.gitlab_func import get_repo_verbose, get_tree
from core.infra.sonarqube_func import get_project_name
from .forms import LabForm
from .models import Course, Lab, Question, Option, Answer
from .utils import get_nav_side_dict, create_user, create_stu_identity, \
    check_stu_lab_status, check_stu_evaluation_status, \
    count_stu_lab_submit, count_stu_evaluation_submit, question_parser
from flow.models import Project
from flow.forms import TemplateRepoForm
from flow.utils import import_template, create_jenkins_job, create_gitlab_webhook, same_name_repo
from flowlab.settings import MEDIA_ROOT


def course_list_view(request):
    """課程總覽"""
    context = {}

    if Role.STUDENT in get_roles(request.user):
        stu_id = Student.objects.filter(user=request.user).get().id
        context.update({'courses': Course.objects.filter(students=stu_id).order_by('id')})
        context.update(get_nav_side_dict(request.user, 'student'))
    elif Role.TEACHER in get_roles(request.user):
        tch_id = Teacher.objects.filter(user=request.user).get().id
        context.update({'courses': Course.objects.filter(teacher=tch_id).order_by('id')})
        context.update(get_nav_side_dict(request.user, 'teacher'))

    return render(request, 'course_list.html', context)


def course_view(request, course_id):
    """課程內容"""
    context = {
        'course_id': course_id,
        'labs': Lab.objects.filter(course=course_id).order_by('id'),
        'course': Course.objects.filter(id=course_id).get(),
        'project': {},
        'lab_submit': {},
        'eva_submit': {},
        'finish': {},
    }
    context.update({'students': context['course'].students.all()})

    if Role.STUDENT in get_roles(request.user):
        for lab in context['labs']:
            student_obj = context['course'].students.filter(user=request.user)
            submit_br = lab.branch
            # 檢查學生 lab 繳交狀態
            student_dict = check_stu_lab_status(lab)
            student = student_dict[request.user.username]
            if student['is_submit']:
                context['lab_submit'].update({
                    lab.name: '✔',
                })
            else:
                context['lab_submit'].update({
                    lab.name: '✖',
                })

            # 檢查學生 評量 填寫狀態
            students_eva = check_stu_evaluation_status(lab)
            student = students_eva[request.user.username]
            if student['is_finish']:
                context['eva_submit'].update({
                    lab.name: '✔',
                })
            else:
                context['eva_submit'].update({
                    lab.name: '✖',
                })

            project = lab.project.filter(user=request.user)
            # 若找的到, lab 對應到'專案名稱'
            if project:
                project_dict = {
                    lab: project.get().name
                }
            # 若找不到, lab 對應到'空值', 前端會顯示'無'
            else:
                project_dict = {
                    lab: ''
                }
            context['project'].update(project_dict)

        context.update(get_nav_side_dict(request.user, 'student'))
        return render(request, 'course_stu.html', context)

    elif Role.TEACHER in get_roles(request.user):
        # 新增單筆學生資料
        if request.method == 'POST' and request.POST['action'] == 'create':
            username = request.POST['username']
            password = request.POST['password']
            name = request.POST['name']
            email = request.POST['email']

            # 建立使用者帳號
            user = create_user(request=request, username=username, password=password, name=name, email=email)
            # 建立學生身份, 並加入課程
            create_success = create_stu_identity(user=user, name=name, course_id=course_id)
            if create_success:
                messages.success(request, MESSAGE_DICT.get('create_stu_in_course_success').format(name))
            else:
                messages.warning(request, MESSAGE_DICT.get('stu_is_in_course').format(name))

        # 批量匯入學生資料
        elif request.method == 'POST' and request.POST['action'] == 'import':
            file_obj = request.FILES.get('file')
            file_path = os.path.join(MEDIA_ROOT, file_obj.name)
            # 將上傳的檔案 存到指定路徑下
            with open(file_path, 'wb') as file:
                for chunk in file_obj.chunks():
                    file.write(chunk)

            with open(file_path, 'r') as file:
                rows = csv.reader(file)
                for row in rows:
                    username = row[0]
                    password = row[1]
                    name = row[2]
                    email = row[3]

                    # 建立使用者帳號
                    user = create_user(request=request, username=username, password=password, name=name, email=email)
                    # 建立學生身份, 並加入課程
                    create_success = create_stu_identity(user=user, name=name, course_id=course_id)

                    if not create_success:
                        messages.warning(request, MESSAGE_DICT.get('stu_is_in_course').format(name))
                messages.success(request, MESSAGE_DICT.get('import_stu_in_course_success'))

            return HttpResponse('OK')

        # 將學生從課程中移除 (不會刪除 gitlab 帳號)
        elif request.method == 'POST' and request.POST['action'] == 'remove':
            # 將學生從課程中移除
            user = User.objects.get(username=request.POST['username'])
            student = Student.objects.get(user=user)
            course = Course.objects.get(id=course_id)
            course.students.remove(student)
            course.save()
            messages.success(request, MESSAGE_DICT.get('remove_stu_in_course_success').format(request.POST['name']))

        for lab in context['labs']:
            students_obj = context['course'].students.all()
            submit_br = lab.branch

            # 計算各 lab 學生繳交人數
            counts = count_stu_lab_submit(lab)
            context['lab_submit'][lab.name] = counts

            # 計算各 評量 學生繳交人數
            counts_eva = count_stu_evaluation_submit(lab)
            context['eva_submit'][lab.name] = counts_eva

        context.update(get_nav_side_dict(request.user, 'teacher'))
        return render(request, 'course_tch.html', context)


def lab_view(request, course_id, lab_id):
    """實驗內容"""
    lab = Lab.objects.filter(id=lab_id).get()
    form = LabForm(instance=lab)

    if Role.STUDENT in get_roles(request.user):
        repo_form = TemplateRepoForm(request.POST or None)

        # 找出與 lab 關聯的專案
        project = lab.project.filter(user=request.user)
        if project:
            project = project.get()

        # 列出有關 user 的所有 gitlab 專案
        gitlab_user = GITLAB_.users.list(username=request.user.username)[0]
        project_list = gitlab_user.projects.list()

        context = {
            'course_id': course_id,
            'lab': lab,
            'project': project,
            'project_list': project_list,
            'form': repo_form,
        }
        context.update(get_nav_side_dict(request.user, 'student'))

        # 按下更新按鈕, 更新關聯專案
        if request.method == 'POST' and request.POST['action'] == 'UpdateRepo':
            origin_repo = request.POST['origin_repo']
            selected_repo = request.POST['select_repo']

            # lab 有關聯到專案, 需要先刪除關聯的專案, 再建立新的關聯專案
            if origin_repo:
                repo_obj = Project.objects.get(user=request.user, name=origin_repo)
                # 刪除關聯的專案
                lab.project.remove(repo_obj)

            if selected_repo == '無':
                messages.success(request, MESSAGE_DICT.get('update_related_project'))
                return redirect('lab', course_id=course_id, lab_id=lab_id)

            # 建立關聯專案
            new_repo_obj = Project.objects.get(user=request.user, name=selected_repo)
            lab.project.add(new_repo_obj)

            context.update({'project': new_repo_obj})
            messages.success(request, MESSAGE_DICT.get('update_related_project'))

        # 使用模板建立新專案 (同時會關聯該專案)
        elif request.method == 'POST' and request.POST['action'] == 'CreateRepo':
            # 擷取常用變數
            username = request.user.username
            repo_name = request.POST['name']
            # 模板檔案
            template_file = lab.template.template

            # 檢查專案是否同名
            if same_name_repo(request, repo_name):
                return redirect('repo_list', user=username)

            # 將模板匯入專案
            project = import_template(
                username=username,
                repo_name=repo_name,
                template_file=template_file,
                description=request.POST['description'],
                visibility=request.POST['visibility'],
            )

            # 建立 Jenkins Job (Multibranch Pipeline 模板)
            create_jenkins_job(username=username, repo_name=repo_name)
            # 建立 GitLab webhook
            create_gitlab_webhook(username=username, repo_name=repo_name, project=project)
            # 建立 SonarQube project
            project_name = get_project_name(username, repo_name)
            SONAR_.projects.create_project(project=project_name, name=project_name)

            # 建立 Project model
            Project.objects.create(**{

course/templates/course.html
{% extends 'base.html' %}
{% block title %}
    課程瀏覽
{% endblock %}
{% block body %}
    <div class="container container_close">
        <div class="content">
            <h1>課程</h1>
            <table class="table table-light table-hover">
                <thead class="table-secondary">
                    <tr>
                        <th scope="col">學期</th>
                        <th scope="col">課程名稱</th>
                        <th scope="col">教師</th>
                    </tr>
                </thead>
                <tbody>
                    {% with course_id=1 %}
                    <tr>
                        <td>110-1</td>
                        <td><a href="{% url 'labs' course_id %}">軟體品質保證測試</a></td>
                        <td>Teacher</td>
                    </tr>
                    <tr>
                        <td>110-1</td>
                        <td>軟體工程理論與實務</td>
                        <td>Teacher</td>
                    </tr>
                    {% endwith %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

course/templates/course_list.html
{% extends 'base.html' %}
{% block title %}
    課程瀏覽
{% endblock %}
{% block body %}
    {% include 'components/sidebar.html' %}
    <div class="container container_close">
        <div class="content">
            <h1>課程</h1>
            <table class="table table-light table-hover">
                <thead class="table-secondary">
                    <tr>
                        <th scope="col">學期</th>
                        <th scope="col">課程名稱</th>
                        <th scope="col">教師</th>
                    </tr>
                </thead>
                <tbody>
                {% for course in courses %}
                    <tr>
                        <td>{{ course.semester }}</td>
                        <td><a href="{% url 'course' course.id %}">{{ course.name }}</a></td>
                        <td>{{ course.teacher }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

course/templates/course_stu.html
{% extends 'base.html' %}
{% block title %}
    {{ course.name }}
{% endblock %}
{% block body %}
    {% include 'components/sidebar.html' %}
    <div class="container container_close">
        <div class="content">
            <h1>{{ course.name }}</h1>
            <h2>Labs</h2>
            <table class="table table-light table-hover">
                <thead class="table-secondary">
                    <tr>
                        <th scope="col">繳交實驗</th>
                        <th scope="col">繳交評量</th>
                        <th scope="col">實驗名稱</th>
                        <th scope="col">關聯專案</th>
                        <th scope="col">繳交分支</th>
                        <th scope="col">繳交期限</th>
                    </tr>
                </thead>
                <tbody>
                {% for lab in labs %}
                    <tr>
                        <td>
                            {% for key, value in lab_submit.items %}
                                {% if key == lab.name %}
                                    {{ value }}
                                {% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            {% for key, value in eva_submit.items %}
                                {% if key == lab.name %}
                                    {{ value }}
                                {% endif %}
                            {% endfor %}
                        </td>
                        <td><a href="{% url 'lab' course.id lab.id %}">{{ lab.name }}</a></td>
                        {% for key, repo in project.items %}
                            {% if key == lab %}
                                {% if repo %}
                                    <td><a href="{% url 'repo_project' user.username repo %}">{{ repo }}</a></td>
                                {% else %}
                                    <td>無</td>
                                {% endif %}
                            {% endif %}
                        {% empty %}
                            <td>無</td>
                        {% endfor %}
                        <td>{{ lab.branch }}</td>
                        <td>{% if lab.deadline %}{{ lab.deadline }}{% else %}無{% endif %}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

course/templates/evaluation_total_tch.html
{% extends 'base.html' %}
{% load static %}
{% load parser %}
{% block title %}
    {{ student }} 互動式評量
{% endblock %}
{% block body %}
    {% include 'components/sidebar.html' %}
    <div class="container container_close">
        <div class="content">
            <div class="row">
                <div class="col-sm-2"></div>
                <div class="col-sm-8"><h2>{{ course.name }} - {{ lab.name }}</h2><br><h1>Self-Report Inventory</h1></div>
                <div class="col-sm-2 d-flex align-items-end"></div>
            </div>
            <h4>Submitted: {{ stu_ans }}　　Unsubmitted: {{ stu_noans }}</h4>
        </div>
    </div>
    <div class="container container_close">
        <div class="content">
            <table class="table table-light table-hover">
                <thead class="table-secondary">
                    <tr>
                        <th class="align-middle" scope="col">Title</th>
                        <th class="align-middle" scope="col">strongly agree</th>
                        <th class="align-middle" scope="col">agree</th>
                        <th class="align-middle" scope="col">average</th>
                        <th class="align-middle" scope="col">disagree</th>
                        <th class="align-middle" scope="col">strongly disagree</th>
                    </tr>
                </thead>
                <tbody>
                    {% for question in questions %}
                        {% if question.type == 'text' %}

                        {% elif question.type == 'single' %}
                            {% for id, options in q_options.items %}
                                <tr>
                                    {% if id == question.id %}
                                        <td>{{ question }}</td>
                                        {% for ans_id, ans in q_ans.items %}
                                            {% if id == ans_id %}
                                                {% for a_id, count in ans.items %}
                                                    <td>{{ count }}</td>
                                                {% endfor %}
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

course/templates/lab_stu.html
{% extends 'base.html' %}
{% load utils %}
{% block title %}
    {{ lab.name }}
{% endblock %}
{% block body %}
    {% include 'components/sidebar.html' %}
    <div class="container container_close">
        <div class="content">
            <h1>{{ lab.name }}</h1>

            {% with display='' %}
            <div class="mb-3 row">
                <label class="col-sm-2 col-form-label text-start">專案</label>
                <div class="px-0 col-sm-8">
                    <div class="card">
                        <div class="card-body-close">
                            <p class="card-text text-start" id="id_repo">
                                {% if project.name %}
                                    <a href="{% url 'repo_project' user.username project.name %}">{{ project.name }}</a>
                                    {% set_value 'none' as display %}
                                {% else %}
                                    無
                                    {% set_value 'block' as display %}
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-2">
                    <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#updateRepo">更新</button>
                </div>
            </div>
            {# 更新 關聯專案 的互動視窗 #}
            <div class="modal fade" id="updateRepo" tabindex="-1" aria-labelledby="updateRepoLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <form method="post">
                            {% csrf_token %}
                            <div class="modal-header">
                                <h5 class="modal-title" id="delModalLabel">請選擇想要更新的專案</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <label for="select_repo" style="display:inline;"></label>
                                <select class="form-select" id="select_repo" name="select_repo">
                                    <option>無</option>
                                {% for repo in project_list %}
                                    <option>{{ repo.name }}</option>
                                {% empty %}
                                    <option>目前儲存庫上沒有任何專案，請先建立專案</option>
                                {% endfor %}
                                </select>
                                <label style="display: none;">
                                    <input name="origin_repo" value="{{ project.name }}">
                                </label>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                                <button type="submit" class="btn btn-primary" name="action" value="UpdateRepo">確定</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div>
                <div class="mb-3 row">
                    <label class="form-label text-start">實驗說明</label>
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text text-start" id="id_description">{% if lab.description %}{{ lab.description }}{% else %}無{% endif %}</p>
                        </div>
                    </div>
                </div>
                <div class="mb-3 row align-items-center">
                    <label class="col-sm-2 col-form-label text-start">實驗繳交分支</label>
                    <div class="px-0 col-sm-10">
                        <div class="card">
                            <div class="card-body-close">
                                <p class="card-text text-start" id="id_branch">{{ lab.branch }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="mb-3 row align-items-center">
                    <label class="col-sm-2 col-form-label text-start">繳交期限</label>
                    <div class="px-0 col-sm-10">
                        <div class="card">
                            <div class="card-body-close">
                                <p class="card-text text-start" id="id_dateline">{% if lab.deadline %}{{ lab.deadline }}{% else %}無{% endif %}</p>
                            </div>
                        </div>
                    </div>
                </div>
                {% if lab.template %}
                    <div class="mb-3 row align-items-center">
                        <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#newModal"
                                style="display: {{ display }}">使用模板建立新專案</button>
                    </div>
                    {# 建立 套用模板的專案 的互動視窗 #}
                    <div class="modal fade" id="newModal" tabindex="-1" aria-labelledby="newModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="newModalLabel">專案資訊</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                    <div class="mb-3 text-start">
                                        <label class="form-label text-start" for="{{ form.name.id_for_label }}">專案名稱</label>
                                        {{ form.name }}
                                    </div>
                                    <div class="mb-3 text-start">
                                        <label class="form-label text-start" for="{{ form.description.id_for_label }}">專案敘述 (選填)</label>
                                        {{ form.description }}
                                    </div>
                                    {% for visible in form.visibility %}
                                    <div class="mb-3 form-check text-start">
                                        {{ visible.tag }}
                                        <label class="form-check-label" for="{{ visible.id_for_label }}">
                                            {{ visible.choice_label.name }}<br>
                                            <span style="color: #5A5A5A;">{{ visible.choice_label.info }}</span>
                                        </label>
                                    </div>
                                    {% endfor %}
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                                        <button type="submit" class="btn btn-primary" name="action" value="CreateRepo">建立專案</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                {% endif %}
            </div>
            {% endwith %}
        </div>
    </div>

    <div class="container container_close">
        <div class="content">
            <a href="{% url 'lab_evaluation' course_id lab.id %}"><button class="btn btn-success">填寫互動式評量</button></a>
        </div>
    </div>
</div>
{% endblock %}